site_name: Monkey Docs
side_url: https://rakzhodekams.github.io/docblog/
site_description: Documentation for Monkeys
site_author: Monkey

repo_url: https://github.com/rakzhodekams/docblog
edit_uri: ""

theme: 
    name: readthedocs
    locale: en
    highlightjs: true
    hljs_languages: 
      - yaml
      - ejs
      - sh
      - javascript
      - markdown

  
