site_name: Monkey Docs
site_url: https://rakzhodekams.github.io/docblog/
site_description: Documentation for Monkeys
site_author: Monkey

repo_url: https://github.com/rakzhodekams/docblog
edit_uri: ""

